#!/usr/bin/env python3
"""Write the complete VPE TypeScript test file.

This script avoids the 'Buffer.from(' pattern in its own source code
by building it dynamically, because the write_file tool corrupts that pattern.
"""
import os

os.chdir('/home/rez/projects/seal/vpe-ts')

# Build the "Buffer.from(...)" pattern dynamically to avoid tool corruption
BUF = "Buffer.fr" + "om('donkeykong_test_secret_2026')"

lines = []
def L(s):
    lines.append(s)

L('/**')
L(' * Tests for seal-vpe: signing, verification, tamper detection.')
L(' * Mirrors the Python test suite at ~/projects/seal/tests/test_core.py')
L(' */')
L('')
L("import * as crypto from 'crypto';")
L('import {')
L('  VPE_VERSION,')
L('  ENVELOPE_FIELDS,')
L('  generateKeyPair,')
L('  canonicalJson,')
L('  vpeSign,')
L('  vpeVerify,')
L('  vpeSignHmac,')
L('  vpeVerifyHmac,')
L('  NonceStore,')
L("} from '../src/index';")
L('')
L('// ---------------------------------------------------------------------------')
L('// Helpers')
L('// ---------------------------------------------------------------------------')
L('')
L(f'const HMAC_SECRET={BUF};')
L('')
L('function makeEnvelope(overrides: Record<string, unknown> = {}): Record<string, unknown> {')
L('  const base: Record<string, unknown> = {')
L("    vpe_version: '1.0',")
L("    prompt: 'hello',")
L('    scope: {},')
L("    issuer: '',")
L("    audience: '',")
L("    doc_sha256: '',")
L('    ttl_seconds: 300,')
L("    nonce: 'abc',")
L('    counter: null,')
L('    cert_chain: null,')
L('  };')
L('  return { ...base, ...overrides };')
L('}')
L('')
L('// ---------------------------------------------------------------------------')
L('// Canonical JSON serialisation')
L('// ---------------------------------------------------------------------------')
L('')
L("describe('CanonicalJSON', () => {")
L("  test('compact no whitespace', () => {")
L('    const env = makeEnvelope();')
L("    const raw = canonicalJson(env).toString('utf-8');")
L("    expect(raw).not.toContain(' ');")
L("    expect(raw).not.toContain('\\n');")
L("    expect(raw).not.toContain(': ');")
L("    expect(raw).not.toContain(', ');")
L('  });')
L('')
L("  test('deterministic', () => {")
L('    const env = makeEnvelope();')
L('    expect(canonicalJson(env)).toEqual(canonicalJson(env));')
L('  });')
L('')
L("  test('field ordering', () => {")
L('    const env = makeEnvelope();')
L("    const raw = canonicalJson(env).toString('utf-8');")
L('    const topKeys = Object.keys(JSON.parse(raw));')
L('    const expected = ENVELOPE_FIELDS.filter(')
L("      (f: any) => f !== 'cert_chain',")
L('    );')
L('    expect(topKeys).toEqual(expected);')
L('  });')
L('')
L("  test('field ordering with cert_chain', () => {")
L('    const env = makeEnvelope({ cert_chain: [{ subject_id: \"leaf\" }] });')
L("    const raw = canonicalJson(env).toString('utf-8');")
L('    const topKeys = Object.keys(JSON.parse(raw));')
L('    const expected = [...ENVELOPE_FIELDS];')
L('    expect(topKeys).toEqual(expected);')
L('  });')
L('')
L("  test('scope keys sorted', () => {")
L('    const env = makeEnvelope({ scope: { z: 1, a: 2, m: 3 } });')
L("    const raw = canonicalJson(env).toString('utf-8');")
L('    const parsed = JSON.parse(raw);')
L('    expect(JSON.stringify(parsed.scope)).toBe(\'{"a":2,"m":3,"z":1}\');')
L('  });')
L('')
L("  test('cert_chain included when present', () => {")
L('    const env = makeEnvelope({ cert_chain: [{ subject_id: \"leaf\" }] });')
L("    const raw = canonicalJson(env).toString('utf-8');")
L('    expect(raw).toContain(\"cert_chain\");')
L('  });')
L('')
L("  test('cert_chain omitted when null', () => {")
L('    const env = makeEnvelope({ cert_chain: null });')
L("    const raw = canonicalJson(env).toString('utf-8');")
L('    expect(raw).not.toContain(\"cert_chain\");')
L('  });')
L('')
L("  test('missing keys resolve to defaults', () => {")
L('    const env: Record<string, unknown> = { prompt: \'hello\' };')
L("    const raw = canonicalJson(env).toString('utf-8');")
L('    expect(raw).toContain(\'\"prompt\"\');')
L('    expect(raw).toContain(\'\"scope\"\');')
L('    expect(raw).toContain(\'\"nonce\"\');')
L('  });')
L('')
L("  test('counter null produces null', () => {")
L('    const env = makeEnvelope({ counter: null });')
L("    const raw = canonicalJson(env).toString('utf-8');")
L('    expect(raw).toContain(\'\"counter\":null\');')
L('  });')
L('')
L("  test('compact lightweight overhead', () => {")
L('    const testCases: [number, number][] = [[1, 200], [50, 250]];')
L('    for (const [plen, expectedMax] of testCases) {')
L("      const env = makeEnvelope({ prompt: 'X'.repeat(plen) });")
L('      const overhead = canonicalJson(env).length;')
L('      expect(overhead).toBeLessThan(expectedMax);')
L('    }')
L('  });')
L('});')
L('')
L('// ---------------------------------------------------------------------------')
L('// Key generation')
L('// ---------------------------------------------------------------------------')
L('')
L("describe('KeyGeneration', () => {")
L("  test('generates 32 byte keys', () => {")
L('    const keys = generateKeyPair();')
L('    expect(keys.privateKey).toHaveLength(32);')
L('    expect(keys.publicKey).toHaveLength(32);')
L('  });')
L('')
L("  test('keys are different', () => {")
L('    const keys = generateKeyPair();')
L('    expect(keys.privateKey).not.toEqual(keys.publicKey);')
L('  });')
L('')
L("  test('consecutive calls differ', () => {")
L('    const a = generateKeyPair();')
L('    const b = generateKeyPair();')
L('    expect(a.privateKey).not.toEqual(b.privateKey);')
L('    expect(a.publicKey).not.toEqual(b.publicKey);')
L('  });')
L('});')
L('')
L('// ---------------------------------------------------------------------------')
L('// Basic signing (Ed25519)')
L('// ---------------------------------------------------------------------------')
L('')
L("describe('Signing', () => {")
L('  let keys: ReturnType<typeof generateKeyPair>;')
L('  beforeEach(() => {')
L('    keys = generateKeyPair();')
L('  });')
L('')
L("  test('sign returns JSON string', () => {")
L("    const env = vpeSign('hello', { privateKey: keys.privateKey });")
L("    expect(typeof env).toBe('string');")
L('  });')
L('')
L("  test('envelope contains all fields', () => {")
L("    const env = vpeSign('hello', { privateKey: keys.privateKey });")
L('    const data = JSON.parse(env);')
L('    const expected = new Set([')
L("      'vpe_version', 'prompt', 'scope', 'issuer', 'audience',")
L("      'doc_sha256', 'iat', 'ttl_seconds', 'nonce', 'counter',")
L("      'cert_chain', 'signature',")
L('    ]);')
L('    expect(new Set(Object.keys(data))).toEqual(expected);')
L('  });')
L('')
L("  test('version is current', () => {")
L("    const env = JSON.parse(vpeSign('hello', { privateKey: keys.privateKey }));")
L('    expect(env.vpe_version).toBe(VPE_VERSION);')
L('  });')
L('')
L("  test('signature is hex string', () => {")
L("    const env = JSON.parse(vpeSign('hello', { privateKey: keys.privateKey }));")
L('    const sig = env.signature as string;')
L("    expect(typeof sig).toBe('string');")
L('    expect(/^[0-9a-f]+$/.test(sig)).toBe(true);')
L('  });')
L('')
L("  test('signature is 64 bytes (128 hex chars)', () => {")
L("    const env = JSON.parse(vpeSign('hello', { privateKey: keys.privateKey }));")
L('    const sig = env.signature as string;')
L('    expect(sig).toHaveLength(128);')
L('  });')
L('')
L("  test('prompt is preserved', () => {")
L("    const env = JSON.parse(vpeSign('my specific prompt', { privateKey: keys.privateKey }));")
L("    expect(env.prompt).toBe('my specific prompt');")
L('  });')
L('')
L("  test('scope is preserved', () => {")
L('    const scope = { allowed_tools: [\'search\', \'read_file\'] };')
L("    const env = JSON.parse(vpeSign('test', { scope, privateKey: keys.privateKey }));")
L('    expect(env.scope).toEqual(scope);')
L('  });')
L('')
L("  test('different prompts different signatures', () => {")
L("    const e1 = JSON.parse(vpeSign('hello', { privateKey: keys.privateKey }));")
L("    const e2 = JSON.parse(vpeSign('world', { privateKey: keys.privateKey }));")
L('    expect(e1.signature).not.toBe(e2.signature);')
L('  });')
L('')
L("  test('different nonces different signatures same prompt', () => {")
L("    const e1 = JSON.parse(vpeSign('hello', { nonce: 'abc', privateKey: keys.privateKey }));")
L("    const e2 = JSON.parse(vpeSign('hello', { nonce: 'xyz', privateKey: keys.privateKey }));")
L('    expect(e1.signature).not.toBe(e2.signature);')
L('  });')
L('')
L("  test('auto generates nonce', () => {")
L("    const env = JSON.parse(vpeSign('hello', { privateKey: keys.privateKey }));")
L('    expect((env.nonce as string).length).toBeGreaterThan(0);')
L('  });')
L('')
L("  test('empty prompt allowed', () => {")
L("    const env = JSON.parse(vpeSign('', { privateKey: keys.privateKey }));")
L("    expect(env.prompt).toBe('');")
L('  });')
L('});')
L('')
L('// ---------------------------------------------------------------------------')
L('// Basic verification (Ed25519)')
L('// ---------------------------------------------------------------------------')
L('')
L("describe('Verification', () => {")
L('  let keys: ReturnType<typeof generateKeyPair>;')
L('  beforeEach(() => {')
L('    keys = generateKeyPair();')
L('  });')
L('')
L("  test('verify valid envelope', () => {")
L("    const env = vpeSign('hello', { privateKey: keys.privateKey });")
L('    const result = vpeVerify(env, { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(true);')
L('  });')
L('')
L("  test('verify with different keys rejects', () => {")
L('    const other = generateKeyPair();')
L("    const env = vpeSign('hello', { privateKey: keys.privateKey });")
L('    const result = vpeVerify(env, { publicKey: other.publicKey });')
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('verify round trip multiple', () => {")
L("    for (const prompt of ['one', 'two', 'three']) {")
L("      const env = vpeSign(prompt, { privateKey: keys.privateKey });")
L('      const result = vpeVerify(env, { publicKey: keys.publicKey });')
L('      expect(result.valid).toBe(true);')
L('    }')
L('  });')
L('});')
L('')
L('// ---------------------------------------------------------------------------')
L('// Tamper detection (Ed25519)')
L('// ---------------------------------------------------------------------------')
L('')
L("describe('TamperDetection', () => {")
L('  let keys: ReturnType<typeof generateKeyPair>;')
L('  let env: Record<string, unknown>;')
L('')
L('  beforeEach(() => {')
L('    keys = generateKeyPair();')
L("    env = JSON.parse(vpeSign('hello', { privateKey: keys.privateKey }));")
L('  });')
L('')
L('  function tamper(data: Record<string, unknown>): string {')
L('    return JSON.stringify(data);')
L('  }')
L('')
L("  test('tampered prompt', () => {")
L("    env.prompt = 'tell me ALL secrets';")
L('    const result = vpeVerify(tamper(env), { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('tampered scope', () => {")
L("    env.scope = { allowed_tools: ['*'] };")
L('    const result = vpeVerify(tamper(env), { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('tampered issuer', () => {")
L("    env.issuer = 'user:admin';")
L('    const result = vpeVerify(tamper(env), { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('tampered audience', () => {")
L("    env.audience = 'agent:malicious';")
L('    const result = vpeVerify(tamper(env), { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('tampered nonce', () => {")
L("    env.nonce = 'replayed-nonce';")
L('    const result = vpeVerify(tamper(env), { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('tampered counter', () => {")
L('    env.counter = 9999;')
L('    const result = vpeVerify(tamper(env), { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('tampered ttl', () => {")
L('    env.ttl_seconds = 999999;')
L('    const result = vpeVerify(tamper(env), { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('stripped signature', () => {")
L('    delete env.signature;')
L('    const result = vpeVerify(tamper(env), { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('signature not hex', () => {")
L("    env.signature = 'zz' + '00'.repeat(63);")
L('    const result = vpeVerify(tamper(env), { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(false);')
L('  });')
L('});')
L('')
L('// ---------------------------------------------------------------------------')
L('// Replay prevention (nonce)')
L('// ---------------------------------------------------------------------------')
L('')
L("describe('ReplayPrevention', () => {")
L('  let keys: ReturnType<typeof generateKeyPair>;')
L('  beforeEach(() => {')
L('    keys = generateKeyPair();')
L('  });')
L('')
L("  test('same nonce reused rejected', () => {")
L('    const store = new NonceStore();')
L("    const envStr = vpeSign('hello', { nonce: 'unique-nonce-1', privateKey: keys.privateKey });")
L('    const result1 = vpeVerify(envStr, { publicKey: keys.publicKey, nonceStore: store });')
L('    expect(result1.valid).toBe(true);')
L("    expect(result1.reason).toBe('ok');")
L('    const result2 = vpeVerify(envStr, { publicKey: keys.publicKey, nonceStore: store });')
L('    expect(result2.valid).toBe(false);')
L("    expect(result2.reason).toBe('nonce_reused');")
L('  });')
L('')
L("  test('different nonces both ok', () => {")
L('    const store = new NonceStore();')
L("    const env1 = vpeSign('hello', { nonce: 'nonce-a', privateKey: keys.privateKey });")
L("    const env2 = vpeSign('hello', { nonce: 'nonce-b', privateKey: keys.privateKey });")
L('    expect(vpeVerify(env1, { publicKey: keys.publicKey, nonceStore: store }).valid).toBe(true);')
L('    expect(vpeVerify(env2, { publicKey: keys.publicKey, nonceStore: store }).valid).toBe(true);')
L('  });')
L('')
L("  test('no nonce store skips replay check', () => {")
L("    const env = vpeSign('hello', { nonce: 'compat-nonce', privateKey: keys.privateKey });")
L('    expect(vpeVerify(env, { publicKey: keys.publicKey }).valid).toBe(true);')
L('    expect(vpeVerify(env, { publicKey: keys.publicKey }).valid).toBe(true);')
L('  });')
L('')
L("  test('ttl zero skips replay check', () => {")
L('    const store = new NonceStore();')
L("    const env = vpeSign('hello', { nonce: 'ttlzero-nonce', ttlSeconds: 0, privateKey: keys.privateKey });")
L('    expect(vpeVerify(env, { publicKey: keys.publicKey, nonceStore: store }).valid).toBe(true);')
L('    expect(vpeVerify(env, { publicKey: keys.publicKey, nonceStore: store }).valid).toBe(true);')
L('  });')
L('')
L("  test('missing nonce rejected', () => {")
L("    const envParsed = JSON.parse(vpeSign('hello', { privateKey: keys.privateKey }));")
L('    delete envParsed.nonce;')
L('    const result = vpeVerify(JSON.stringify(envParsed), { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('empty nonce rejected', () => {")
L("    const env = vpeSign('hello', { nonce: '', privateKey: keys.privateKey });")
L('    const result = vpeVerify(env, { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('nonce is string', () => {")
L("    const env = JSON.parse(vpeSign('hello', { nonce: 'abc', privateKey: keys.privateKey }));")
L("    expect(typeof env.nonce).toBe('string');")
L('  });')
L('});')
L('')
L('// ---------------------------------------------------------------------------')
L('// Counter')
L('// ---------------------------------------------------------------------------')
L('')
L("describe('Counter', () => {")
L('  let keys: ReturnType<typeof generateKeyPair>;')
L('  beforeEach(() => {')
L('    keys = generateKeyPair();')
L('  });')
L('')
L("  test('counter accepted when present', () => {")
L("    const env = vpeSign('hello', { counter: 42, privateKey: keys.privateKey });")
L('    const result = vpeVerify(env, { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(true);')
L('  });')
L('')
L("  test('counter optional', () => {")
L("    const env = vpeSign('hello', { privateKey: keys.privateKey });")
L('    const result = vpeVerify(env, { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(true);')
L('  });')
L('')
L("  test('counter tampered', () => {")
L("    const envParsed = JSON.parse(vpeSign('hello', { counter: 42, privateKey: keys.privateKey }));")
L('    envParsed.counter = 99;')
L('    const result = vpeVerify(JSON.stringify(envParsed), { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('counter non integer rejected', () => {")
L("    const envParsed = JSON.parse(vpeSign('hello', { counter: 42, privateKey: keys.privateKey }));")
L("    envParsed.counter = 'not-an-int';")
L('    const result = vpeVerify(JSON.stringify(envParsed), { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(false);')
L('  });')
L('});')
L('')
L('// ---------------------------------------------------------------------------')
L('// Scope')
L('// ---------------------------------------------------------------------------')
L('')
L("describe('ScopeVerification', () => {")
L('  let keys: ReturnType<typeof generateKeyPair>;')
L('  beforeEach(() => {')
L('    keys = generateKeyPair();')
L('  });')
L('')
L("  test('scope must be dict', () => {")
L("    const envParsed = JSON.parse(vpeSign('hello', { scope: { a: 1 }, privateKey: keys.privateKey }));")
L("    envParsed.scope = 'not-a-dict';")
L('    const result = vpeVerify(JSON.stringify(envParsed), { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('scope verifies when valid', () => {")
L("    const scope = { allowed_tools: ['read_file'] };")
L("    const env = vpeSign('hello', { scope, privateKey: keys.privateKey });")
L('    const result = vpeVerify(env, { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(true);')
L('  });')
L('')
L("  test('empty scope allowed', () => {")
L("    const env = vpeSign('hello', { scope: {}, privateKey: keys.privateKey });")
L('    const result = vpeVerify(env, { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(true);')
L('  });')
L('});')
L('')
L('// ---------------------------------------------------------------------------')
L('// Scope & field escalation attacks')
L('// ---------------------------------------------------------------------------')
L('')
L("describe('ScopeEscalation', () => {")
L('  let keys: ReturnType<typeof generateKeyPair>;')
L('  let env: Record<string, unknown>;')
L('')
L('  beforeEach(() => {')
L('    keys = generateKeyPair();')
L('    env = JSON.parse(')
L("      vpeSign('search for customer X',")
L('        {')
L("          scope: { allowed_tools: ['search'], max_tokens: 2000 },")
L("          issuer: 'user:alice',")
L("          audience: 'agent:hermes-default',")
L('          ttlSeconds: 300,')
L('          privateKey: keys.privateKey,')
L('        },')
L('      ),')
L('    );')
L('  });')
L('')
L('  function tamper(data: Record<string, unknown>): string {')
L('    return JSON.stringify(data);')
L('  }')
L('')
L('  function verify(tamperedStr: string): ReturnType<typeof vpeVerify> {')
L('    return vpeVerify(tamperedStr, { publicKey: keys.publicKey });')
L('  }')
L('')
L("  test('scope entirely replaced after signing', () => {")
L("    env.scope = { allowed_tools: ['*'] };")
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('')
L("  test('scope restrictions removed emptied', () => {")
L('    env.scope = {};')
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('')
L("  test('scope allowed_tools popped', () => {")
L("    env.scope = { allowed_tools: [] };")
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('')
L("  test('scope max_tokens inflated', () => {")
L("    env.scope = { allowed_tools: ['search'], max_tokens: 999999 };")
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('')
L("  test('scope extra domains injected', () => {")
L("    (env.scope as Record<string, unknown>).allowed_domains = ['*.evil.com'];")
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('')
L("  test('scope as null', () => {")
L('    env.scope = null;')
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('')
L("  test('scope as list', () => {")
L('    env.scope = [1, 2, 3];')
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('')
L("  test('extra tools appended', () => {")
L("    (env.scope as Record<string, unknown>).allowed_tools = ['search', 'delete_all'];")
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('')
L("  test('extra tools prepended', () => {")
L("    (env.scope as Record<string, unknown>).allowed_tools = ['delete_all', 'search'];")
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('')
L("  test('all wildcard tools', () => {")
L("    (env.scope as Record<string, unknown>).allowed_tools = ['*'];")
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('')
L("  test('ttl extended long', () => {")
L('    env.ttl_seconds = 86400 * 365;')
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('')
L("  test('ttl extended to infinite', () => {")
L('    env.ttl_seconds = 0;')
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('')
L("  test('ttl extended negative', () => {")
L('    env.ttl_seconds = -1;')
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('')
L("  test('audience redirected', () => {")
L("    env.audience = 'agent:malicious-actor';")
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('')
L("  test('issuer spoofed', () => {")
L("    env.issuer = 'user:admin';")
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('')
L("  test('audience and issuer swapped', () => {")
L('    [env.audience, env.issuer] = [env.issuer, env.audience];')
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('')
L("  test('multi field escalation', () => {")
L("    env.scope = { allowed_tools: ['*'] };")
L('    env.ttl_seconds = 999999;')
L("    env.audience = 'agent:eve';")
L("    env.issuer = 'user:eve';")
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('')
L("  test('scope cert_chain injected', () => {")
L('    env.cert_chain = [')
L("      { subject_id: 'ca:attacker-root', subject_public_key: '00'.repeat(32), issuer_id: 'ca:attacker-root', issuer_public_key: '00'.repeat(32) },")
L('    ];')
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('')
L("  test('doc_sha256 rewritten', () => {")
L("    env.doc_sha256 = 'deadbeef'.repeat(8);")
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('')
L("  test('vpe_version downgrade', () => {")
L("    env.vpe_version = '0.1';")
L('    expect(verify(tamper(env)).valid).toBe(false);')
L('  });')
L('});')
L('')
L('// ---------------------------------------------------------------------------')
L('// TTL')
L('// ---------------------------------------------------------------------------')
L('')
L("describe('TTL', () => {")
L('  let keys: ReturnType<typeof generateKeyPair>;')
L('  beforeEach(() => {')
L('    keys = generateKeyPair();')
L('  });')
L('')
L("  test('ttl zero means no expiry', () => {")
L("    const env = vpeSign('hello', { ttlSeconds: 0, privateKey: keys.privateKey });")
L('    const result = vpeVerify(env, { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(true);')
L('  });')
L('')
L("  test('ttl preserved in envelope', () => {")
L("    const env = JSON.parse(vpeSign('hello', { ttlSeconds: 120, privateKey: keys.privateKey }));")
L('    expect(env.ttl_seconds).toBe(120);')
L('  });')
L('')
L("  test('ttl non integer rejected', () => {")
L("    const envParsed = JSON.parse(vpeSign('hello', { ttlSeconds: 120, privateKey: keys.privateKey }));")
L("    envParsed.ttl_seconds = 'not-an-int';")
L('    const result = vpeVerify(JSON.stringify(envParsed), { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('default ttl is 300', () => {")
L("    const env = JSON.parse(vpeSign('hello', { privateKey: keys.privateKey }));")
L('    expect(env.ttl_seconds).toBe(300);')
L('  });')
L('});')
L('')
L('// ---------------------------------------------------------------------------')
L('// Edge cases')
L('// ---------------------------------------------------------------------------')
L('')
L("describe('EdgeCases', () => {")
L('  let keys: ReturnType<typeof generateKeyPair>;')
L('  beforeEach(() => {')
L('    keys = generateKeyPair();')
L('  });')
L('')
L("  test('invalid json', () => {")
L("    const result = vpeVerify('not json', { publicKey: keys.publicKey });")
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('json not dict', () => {")
L("    const result = vpeVerify('[]', { publicKey: keys.publicKey });")
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('wrong version', () => {")
L("    const envParsed = JSON.parse(vpeSign('hello', { privateKey: keys.privateKey }));")
L("    envParsed.vpe_version = '0.9';")
L('    const result = vpeVerify(JSON.stringify(envParsed), { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('missing signature field', () => {")
L("    const envParsed = JSON.parse(vpeSign('hello', { privateKey: keys.privateKey }));")
L('    delete envParsed.signature;')
L('    const result = vpeVerify(JSON.stringify(envParsed), { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('long prompt round trip', () => {")
L("    const prompt = 'A'.repeat(100_000);")
L("    const env = vpeSign(prompt, { privateKey: keys.privateKey });")
L('    const result = vpeVerify(env, { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(true);')
L('  });')
L('')
L("  test('unicode prompt', () => {")
L("    const prompt = '\\u65e5\\u672c\\u8a9e \\u{1F680}';")
L("    const env = vpeSign(prompt, { privateKey: keys.privateKey });")
L('    const result = vpeVerify(env, { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(true);')
L('  });')
L('});')
L('')
L('// ---------------------------------------------------------------------------')
L('// Key time constraints (not_before / not_after)')
L('// ---------------------------------------------------------------------------')
L('')
L("describe('KeyTimeConstraints', () => {")
L('  let keys: ReturnType<typeof generateKeyPair>;')
L('  beforeEach(() => {')
L('    keys = generateKeyPair();')
L('  });')
L('')
L("  test('not_before rejects early', () => {")
L("    const env = vpeSign('hello', { privateKey: keys.privateKey });")
L('    const result = vpeVerify(env, {')
L('      publicKey: keys.publicKey,')
L('      notBefore: Math.floor(Date.now() / 1000) + 99999,')
L('    });')
L('    expect(result.valid).toBe(false);')
L("    expect(result.reason).toContain('key_not_yet_valid');")
L('  });')
L('')
L("  test('not_before passes when valid', () => {")
L("    const env = vpeSign('hello', { privateKey: keys.privateKey });")
L('    const result = vpeVerify(env, {')
L('      publicKey: keys.publicKey,')
L('      notBefore: Math.floor(Date.now() / 1000) - 99999,')
L('    });')
L('    expect(result.valid).toBe(true);')
L('  });')
L('')
L("  test('not_after rejects expired', () => {")
L("    const env = vpeSign('hello', { privateKey: keys.privateKey });")
L('    const result = vpeVerify(env, {')
L('      publicKey: keys.publicKey,')
L('      notAfter: Math.floor(Date.now() / 1000) - 1,')
L('    });')
L('    expect(result.valid).toBe(false);')
L("    expect(result.reason).toContain('key_expired');")
L('  });')
L('')
L("  test('not_after passes when not expired', () => {")
L("    const env = vpeSign('hello', { privateKey: keys.privateKey });")
L('    const result = vpeVerify(env, {')
L('      publicKey: keys.publicKey,')
L('      notAfter: Math.floor(Date.now() / 1000) + 99999,')
L('    });')
L('    expect(result.valid).toBe(true);')
L('  });')
L('});')
L('')
L('// ---------------------------------------------------------------------------')
L('// HMAC signing')
L('// ---------------------------------------------------------------------------')
L('')
L("describe('HMACSigning', () => {")
L("  test('sign returns JSON string', () => {")
L("    const env = vpeSignHmac('hello', { sharedSecret: HMAC_SECRET });")
L("    expect(typeof env).toBe('string');")
L('  });')
L('')
L("  test('envelope contains all fields', () => {")
L("    const env = vpeSignHmac('hello', { sharedSecret: HMAC_SECRET });")
L('    const data = JSON.parse(env);')
L('    const expected = new Set([')
L("      'vpe_version', 'prompt', 'scope', 'issuer', 'audience',")
L("      'doc_sha256', 'iat', 'ttl_seconds', 'nonce', 'counter', 'signature',")
L('    ]);')
L('    expect(new Set(Object.keys(data))).toEqual(expected);')
L('  });')
L('')
L("  test('signature is 32 bytes (64 hex chars)', () => {")
L("    const env = JSON.parse(vpeSignHmac('hello', { sharedSecret: HMAC_SECRET }));")
L('    const sig = env.signature as string;')
L('    expect(sig).toHaveLength(64);')
L('  });')
L('')
L("  test('prompt is preserved', () => {")
L("    const env = JSON.parse(vpeSignHmac('hello wally', { sharedSecret: HMAC_SECRET }));")
L("    expect(env.prompt).toBe('hello wally');")
L('  });')
L('')
L("  test('scope is preserved', () => {")
L("    const scope = { allowed_tools: ['read_file'] };")
L("    const env = JSON.parse(vpeSignHmac('test', { scope, sharedSecret: HMAC_SECRET }));")
L('    expect(env.scope).toEqual(scope);')
L('  });')
L('')
L("  test('different prompts different signatures', () => {")
L("    const e1 = JSON.parse(vpeSignHmac('hello', { sharedSecret: HMAC_SECRET }));")
L("    const e2 = JSON.parse(vpeSignHmac('world', { sharedSecret: HMAC_SECRET }));")
L('    expect(e1.signature).not.toBe(e2.signature);')
L('  });')
L('')
L("  test('empty prompt allowed', () => {")
L("    const env = JSON.parse(vpeSignHmac('', { sharedSecret: HMAC_SECRET }));")
L("    expect(env.prompt).toBe('');")
L('  });')
L('')
L("  test('empty shared secret rejected', () => {")
L('    expect(() => {')
L("      vpeSignHmac('hello', { sharedSecret: " + BUF.replace("donkeykong_test_secret_2026", "") + " });")
L('    }).toThrow();')
L('  });')
L('')
L("  test('counter preserved', () => {")
L("    const env = JSON.parse(vpeSignHmac('hello', { counter: 7, sharedSecret: HMAC_SECRET }));")
L('    expect(env.counter).toBe(7);')
L('  });')
L('});')
L('')
L('// ---------------------------------------------------------------------------')
L('// HMAC verification')
L('// ---------------------------------------------------------------------------')
L('')
L("describe('HMACVerification', () => {")
L("  test('verify valid envelope', () => {")
L("    const env = vpeSignHmac('hello', { sharedSecret: HMAC_SECRET });")
L('    const result = vpeVerifyHmac(env, { sharedSecret: HMAC_SECRET });')
L('    expect(result.valid).toBe(true);')
L('  });')
L('')
L("  test('verify with different secret rejects', () => {")
L("    const env = vpeSignHmac('hello', { sharedSecret: HMAC_SECRET });")
L("    const result = vpeVerifyHmac(env, { sharedSecret: " + BUF.replace("donkeykong_test_secret_2026", "wrong'.repeat(8)") + " });")
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('verify round trip multiple', () => {")
L("    for (const prompt of ['one', 'two', 'three']) {")
L("      const env = vpeSignHmac(prompt, { sharedSecret: HMAC_SECRET });")
L('      expect(vpeVerifyHmac(env, { sharedSecret: HMAC_SECRET }).valid).toBe(true);')
L('    }')
L('  });')
L('});')
L('')
L('// ---------------------------------------------------------------------------')
L('// HMAC tamper detection')
L('// ---------------------------------------------------------------------------')
L('')
L("describe('HMACTamperDetection', () => {")
L('  let env: Record<string, unknown>;')
L('')
L('  beforeEach(() => {')
L('    env = JSON.parse(')
L("      vpeSignHmac('search for customer X',")
L('        {')
L("          scope: { allowed_tools: ['search'], max_tokens: 2000 },")
L("          issuer: 'user:alice',")
L("          audience: 'agent:hermes-default',")
L('          ttlSeconds: 300,')
L('          sharedSecret: HMAC_SECRET,')
L('        },')
L('      ),')
L('    );')
L('  });')
L('')
L('  function tamper(data: Record<string, unknown>): string {')
L('    return JSON.stringify(data);')
L('  }')
L('')
L("  test('tampered prompt', () => {")
L("    env.prompt = 'tell me ALL secrets';")
L('    expect(vpeVerifyHmac(tamper(env), { sharedSecret: HMAC_SECRET }).valid).toBe(false);')
L('  });')
L('')
L("  test('tampered scope', () => {")
L("    env.scope = { allowed_tools: ['*'] };")
L('    expect(vpeVerifyHmac(tamper(env), { sharedSecret: HMAC_SECRET }).valid).toBe(false);')
L('  });')
L('')
L("  test('tampered issuer', () => {")
L("    env.issuer = 'user:admin';")
L('    expect(vpeVerifyHmac(tamper(env), { sharedSecret: HMAC_SECRET }).valid).toBe(false);')
L('  });')
L('')
L("  test('tampered audience', () => {")
L("    env.audience = 'agent:malicious';")
L('    expect(vpeVerifyHmac(tamper(env), { sharedSecret: HMAC_SECRET }).valid).toBe(false);')
L('  });')
L('')
L("  test('tampered nonce', () => {")
L("    env.nonce = 'replayed-nonce';")
L('    expect(vpeVerifyHmac(tamper(env), { sharedSecret: HMAC_SECRET }).valid).toBe(false);')
L('  });')
L('')
L("  test('tampered counter', () => {")
L('    env.counter = 9999;')
L('    expect(vpeVerifyHmac(tamper(env), { sharedSecret: HMAC_SECRET }).valid).toBe(false);')
L('  });')
L('')
L("  test('tampered ttl', () => {")
L('    env.ttl_seconds = 999999;')
L('    expect(vpeVerifyHmac(tamper(env), { sharedSecret: HMAC_SECRET }).valid).toBe(false);')
L('  });')
L('')
L("  test('stripped signature', () => {")
L('    delete env.signature;')
L('    expect(vpeVerifyHmac(tamper(env), { sharedSecret: HMAC_SECRET }).valid).toBe(false);')
L('  });')
L('')
L("  test('missing nonce', () => {")
L('    delete env.nonce;')
L('    expect(vpeVerifyHmac(tamper(env), { sharedSecret: HMAC_SECRET }).valid).toBe(false);')
L('  });')
L('});')
L('')
L('// ---------------------------------------------------------------------------')
L('// HMAC edge cases')
L('// ---------------------------------------------------------------------------')
L('')
L("describe('HMACEdgeCases', () => {")
L("  test('empty envelope prompt', () => {")
L("    const env = vpeSignHmac('', { sharedSecret: HMAC_SECRET });")
L('    expect(vpeVerifyHmac(env, { sharedSecret: HMAC_SECRET }).valid).toBe(true);')
L('  });')
L('')
L("  test('long prompt', () => {")
L("    const env = vpeSignHmac('A'.repeat(100_000), { sharedSecret: HMAC_SECRET });")
L('    expect(vpeVerifyHmac(env, { sharedSecret: HMAC_SECRET }).valid).toBe(true);')
L('  });')
L('')
L("  test('invalid json', () => {")
L("    const result = vpeVerifyHmac('not json', { sharedSecret: HMAC_SECRET });")
L('    expect(result.valid).toBe(false);')
L('  });')
L('')
L("  test('wrong version', () => {")
L("    const parsed = JSON.parse(vpeSignHmac('hello', { sharedSecret: HMAC_SECRET }));")
L("    parsed.vpe_version = '0.9';")
L('    const result = vpeVerifyHmac(JSON.stringify(parsed), { sharedSecret: HMAC_SECRET });')
L('    expect(result.valid).toBe(false);')
L('  });')
L('});')
L('')
L('// ---------------------------------------------------------------------------')
L('// Compact mode tests')
L('// ---------------------------------------------------------------------------')
L('')
L("describe('CompactMode', () => {")
L('  let keys: ReturnType<typeof generateKeyPair>;')
L('  beforeEach(() => {')
L('    keys = generateKeyPair();')
L('  });')
L('')
L("  test('compact strips defaults', () => {")
L('    const env = JSON.parse(')
L("      vpeSign('hello', {")
L('        privateKey: keys.privateKey,')
L('        compact: true,')
L("        issuer: '',")
L("        audience: '',")
L('      }),')
L('    );')
L('    expect(env.issuer).toBeUndefined();')
L('    expect(env.audience).toBeUndefined();')
L('    expect(env.vpe_version).toBeUndefined();')
L("    expect(env.prompt).toBe('hello');")
L('    expect(env.signature).toBeDefined();')
L('    expect(env.nonce).toBeDefined();')
L('  });')
L('')
L("  test('compact preserves non-default values', () => {")
L('    const env = JSON.parse(')
L("      vpeSign('hello', {")
L('        privateKey: keys.privateKey,')
L("        issuer: 'user:test',")
L("        audience: 'agent:test',")
L('        ttlSeconds: 600,')
L('        compact: true,')
L('      }),')
L('    );')
L("    expect(env.issuer).toBe('user:test');")
L("    expect(env.audience).toBe('agent:test');")
L('    expect(env.ttl_seconds).toBe(600);')
L('  });')
L('')
L("  test('compact mode verifies transparently', () => {")
L("    const env = vpeSign('hello', {")
L('      privateKey: keys.privateKey,')
L('      compact: true,')
L('    });')
L('    const result = vpeVerify(env, { publicKey: keys.publicKey });')
L('    expect(result.valid).toBe(true);')
L('  });')
L('')
L("  test('compact mode with HMAC verifies transparently', () => {")
L("    const env = vpeSignHmac('hello', {")
L('      sharedSecret: HMAC_SECRET,')
L('      compact: true,')
L('    });')
L('    const result = vpeVerifyHmac(env, { sharedSecret: HMAC_SECRET });')
L('    expect(result.valid).toBe(true);')
L('  });')
L('});')

# Write the file
with open('tests/core.test.ts', 'w') as f:
    f.write('\n'.join(lines) + '\n')

size = os.path.getsize('tests/core.test.ts')
print(f'Wrote {len(lines)} lines, {size} bytes')

# Verify line 23
with open('tests/core.test.ts') as f:
    for i, line in enumerate(f, 1):
        if i == 23:
            print(f'Line 23: {line.rstrip()!r}')
        if i == 24:
            print(f'Line 24: {line.rstrip()!r}')
